version = 0.1

[default.deploy.parameters]
stack_name = "ailment-tracker-stack"
resolve_s3 = true
s3_prefix = "ailment-tracker"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev ProjectName=ailment-tracker"
